<Project>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

    <ItemGroup>
   		<Using Include="Bullseye" />
   		<Using Include="SimpleExec" />
    	<Using Include="PipelineTargets" />
      	<Using Include="PipelineTargets.Targets" />
      	<Using Include="PipelineTargets.PipelineCommand" Static="True" />
        <Using Include="PipelineTargets.DotNetTool" Static="True" />

  		<!-- <Using Include="Bullseye.Targets" Static="True" /> -->
  		<Using Include="SimpleExec.Command" Static="True" />
    </ItemGroup>

</Project>
