<Project>

    <PropertyGroup>
    	<ImplicitUsings>enable</ImplicitUsings>
     	<nullable>enable</nullable>
    </PropertyGroup>

    <ItemGroup>
   		<Using Include="Bullseye" />
   		<Using Include="SimpleExec" />
      	<Using Include="Targets" />

  		<!-- <Using Include="Bullseye.Targets" Static="True" /> -->
  		<Using Include="SimpleExec.Command" Static="True" />
    </ItemGroup>

</Project>
